version: 2
updates:
  - package-ecosystem: npm
    directory: /api
    schedule:
      interval: daily
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /api
    schedule:
      interval: daily
